<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6r8XMVF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6r8XMVF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6r8XMVF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6r8XMVF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6r8XMVF\App_KernelDevDebugContainer([
    'container.build_hash' => '6r8XMVF',
    'container.build_id' => '3773ee25',
    'container.build_time' => 1685169887,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6r8XMVF');
